name: bopy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install DIRECT dependencies
        run: |
          sudo apt-get install gfortran -y
      - name: Install bopy dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --system
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
